# Generated by Django 4.2.4 on 2023-08-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_dashboard_update_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='advisor',
            field=models.CharField(default='Default Advisor Name', max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='student_counter',
            field=models.IntegerField(default=0),
        ),
    ]
