# Generated by Django 4.2.4 on 2023-08-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='button_url',
        ),
        migrations.RemoveField(
            model_name='link',
            name='iframe_url',
        ),
        migrations.AddField(
            model_name='link',
            name='thumbnail_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='zoom_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
