# Generated by Django 4.2.4 on 2023-08-16 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_link_button_url_remove_link_iframe_url_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Link',
            new_name='uploadLink',
        ),
    ]
