# Generated by Django 4.2.4 on 2023-08-16 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_rename_link_uploadlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadlink',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.teacher'),
        ),
    ]
