# Generated by Django 4.2.4 on 2023-08-16 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_uploadlink_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadlink',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'user_type': 2}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
