# Generated by Django 4.2.4 on 2023-08-27 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_uploadlink_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='zoom_link',
            new_name='board_link',
        ),
    ]
