# Generated by Django 4.2.4 on 2023-08-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_rename_zoom_link_video_board_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadlink',
            name='board_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
