# Generated by Django 4.2.4 on 2023-11-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_uploadlink_board_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
