# Generated by Django 4.2.4 on 2023-08-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quiz_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='total_marks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
