# Generated by Django 4.2.4 on 2023-08-15 20:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_quiz_total_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
